### ISSUE TITLE
Nothing happens?

### ISSUE THREAD

**Issue by FezVrasta** [samccone/bundle-buddy#29]
Hi, when I run `bundle-buddy`, after 3 minutes of doing something, it exits with `"no bundle duplication detected" and nothing else happens, how do I open the UI?

My bundle is quite large.

**Comment by samccone** [comment]
Hey @FezVrasta no bundle duplication is a good thing :) it means bundle buddy has nothing to really show you.

In this case what would you like bundle-buddy to show?

cc @susielu

**Comment by FezVrasta** [comment]
I'm 100% sure my code base is full of... emh, shit.

But anyway, I would expect to be able to see the charts?

**Comment by susielu** [comment]
Would you be able to share the repo w/us so we could use it as an example to test this case with?

**Comment by samccone** [comment]
related https://github.com/samccone/bundle-buddy/issues/25

**Comment by FezVrasta** [comment]
nope unfortunately I can't share it 🙁

**Comment by zdrummond** [comment]
@samccone I will quickly chime-in; I know Bundle Buddy is about duplication, but it also feels like your base UI could be easily adapted to be a better `source-map-explorer`. I am glad I don't have dups, but dups is only one part in the path to lose weight. One tool to do it all (or at least more) would be nice, and it seems like you are close to that.

**Comment by samccone** [comment]
Hey @zdrummond I totally agree. This has been something @susielu and I have talked about tackling .. With the goal being to make bundle-buddy a one-stop-shop for exploring exactly is in your bundle.

Thanks!

**Comment by montogeek** [comment]
I would like to see this project become a better `source-map-explorer`, maybe adding a flag or showing a source map visualization even if there is not duplication, this is too good to dont use it as a bundle analyzer/visualizer/explorer.

Any plans @samccone ? I would gladly help!

**Comment by samccone** [comment]
hey @montogeek, @susielu and I have been working up some ideas on how to do this and how to create a valuable viz for bundles.

Thanks for your interest! we will be sure to file some mocks when we arrive at something.

**Comment by stereobooster** [comment]
Same here. I will try to create simple example, meantime I will explain. I have create-react-app application with following code:

```js
import Loadable from "react-loadable";
const PhoneAsync = Loadable({
  loader: () => import("react-phone-number-input"),
  loading: () => <span>Loading the phone number</span>
});
```

webpack creates two files: main.js and chunk.js. Both of those files contain copy of ReactDOM because of this issue https://github.com/catamphetamine/react-phone-number-input/issues/98 (or source-map-explorer is lying)

**Comment by catamphetamine** [comment]
> Both of those files contain copy of ReactDOM because of this issue catamphetamine/react-phone-number-input#98

To clarify for others: this is not an issue of any sort.
`react-dom` gets bundled anyway in a web browser.

**Comment by stereobooster** [comment]
yes this is an issue, It delivers two copies of of `ReactDOM`

**Comment by catamphetamine** [comment]
> yes this is an issue, It delivers two copies of of ReactDOM

this is an issue, but not the issue you reported.
it's an issue with your bundling process.

**Comment by stereobooster** [comment]
yes and this is repository of the tool which is analyse bundler output, which should show issues of bundler.

**Comment by samccone** [comment]
Hey all, here is the design document for the next addition to bundle-buddy
https://docs.google.com/document/d/1ycGVBJmwIVs34yhC0oTqv_WH5f0fs2SAFmzyTiBK99k/edit#

Comments and thoughts are welcome.

**Comment by stereobooster** [comment]
> Existing tools for understanding a single bundle

Add this to the list https://webpack.github.io/analyse

> User questions

What introduced this dependency? Example: I see lodash.js in my bundle, but I haven't added it. It appears that libx uses it and LibX required by MobX.

---

Also, I wonder if it is possible to implement library which will recommend improvements like:

- use ES6 methods instead of lodash. See [underdash](https://surma.github.io/underdash/), [You-Dont-Know-Lodash-Underscore](https://github.com/you-dont-need/You-Dont-Know-Lodash-Underscore)
- detect if packages have type signatures and recommend to use Google Closure Compiler in advanced mode. For example, there are a lot of type signatures in DefinetlyTyped repo, [assume we can successfully convert from TypeScript to Closure JSDoc](https://github.com/stereobooster/type-o-rama#typescript-to-closure-jsdoc), then we can use advanced mode Closure and shake off more
